/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Welcome
         * @description Default root route provided by h4ckath0n.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_api_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rbac": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rbac */
        get: operations["get_rbac_api_rbac_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rbac/{node_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Rbac */
        post: operations["revoke_rbac_api_rbac__node_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topology */
        get: operations["get_topology_api_topology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Scan */
        post: operations["run_scan_api_topology_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology/{node_id}/isolate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Isolate Node */
        post: operations["isolate_node_api_topology__node_id__isolate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vulnerabilities */
        get: operations["get_vulnerabilities_api_vulnerabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with password
         * @description Verify email and password, then bind an optional device key.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/add/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish adding a passkey
         * @description Verify the WebAuthn attestation and attach the new passkey to the user.
         */
        post: operations["add_finish_auth_passkey_add_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/add/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start adding a passkey
         * @description Begin adding a new passkey for the authenticated user and return registration options.
         */
        post: operations["add_start_auth_passkey_add_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish passkey login
         * @description Finish passkey login by verifying the WebAuthn assertion for the flow and binding an optional device key.
         */
        post: operations["login_finish_auth_passkey_login_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/login/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start passkey login
         * @description Begin a username-less passkey login ceremony and return WebAuthn authentication options.
         */
        post: operations["login_start_auth_passkey_login_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/register/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish passkey registration
         * @description Finish passkey registration by verifying the WebAuthn attestation for the flow and binding an optional device key.
         */
        post: operations["register_finish_auth_passkey_register_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/register/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start passkey registration
         * @description Begin a passkey registration ceremony. Creates a new user and a single-use challenge flow, then returns WebAuthn registration options.
         */
        post: operations["register_start_auth_passkey_register_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List passkeys
         * @description List all passkeys, including revoked entries, for the current user.
         */
        get: operations["passkeys_list_auth_passkeys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a passkey
         * @description Update the user-facing name of a passkey.
         */
        patch: operations["passkey_rename_auth_passkeys__key_id__patch"];
        trace?: never;
    };
    "/auth/passkeys/{key_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a passkey
         * @description Revoke a passkey by its internal key ID. The last active passkey cannot be revoked and returns the LAST_PASSKEY error.
         */
        post: operations["passkey_revoke_auth_passkeys__key_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm password reset
         * @description Confirm a password reset token, set a new password, and bind an optional device key.
         */
        post: operations["password_reset_confirm_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Request a password reset token for the account. Returns the same message even when the email is unknown.
         */
        post: operations["password_reset_request_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register with password
         * @description Create a new account using email and password, then bind an optional device key.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cadvisor/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Cadvisor Batch */
        post: operations["ingest_cadvisor_batch_cadvisor_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/echo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo echo
         * @description Echo back the message along with its reverse.
         */
        post: operations["demo_echo_demo_echo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo ping
         * @description Simple liveness ping for the demo namespace.
         */
        get: operations["demo_ping_demo_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo SSE stream
         * @description Authenticated SSE stream that simulates chunked output. Requires a device JWT with aud set to h4ckath0n:sse.
         */
        get: operations["demo_sse_demo_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Basic health check for the app.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Readiness check for E2E and deployment probes.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jobs */
        get: operations["get_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/llm/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_llm_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Uploads */
        get: operations["get_uploads_uploads_get"];
        put?: never;
        /** Create Upload */
        post: operations["create_upload_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_upload_uploads_post */
        Body_create_upload_uploads_post: {
            /** File */
            file: string;
        };
        /** CadvisorBatchPayloadSchema */
        CadvisorBatchPayloadSchema: {
            /** Machine Name */
            machine_name: string;
            /** Samples */
            samples: components["schemas"]["CadvisorSampleSchema"][];
            /** Schema Version */
            schema_version: string;
            /** Sent At */
            sent_at: string;
            /** Source */
            source: {
                [key: string]: string;
            };
        };
        /** CadvisorSampleSchema */
        CadvisorSampleSchema: {
            container_reference: components["schemas"]["ContainerReferenceSchema"];
            /** Container Spec */
            container_spec?: {
                [key: string]: unknown;
            } | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
        };
        /** ContainerReferenceSchema */
        ContainerReferenceSchema: {
            /** Aliases */
            aliases?: string[] | null;
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
        };
        /** DeviceBindingResponse */
        DeviceBindingResponse: {
            /**
             * Device Id
             * @description Device ID that starts with the d prefix, empty when no device key is bound.
             */
            device_id: string;
            /**
             * Role
             * @description Server-side role for the user.
             */
            role: string;
            /**
             * User Id
             * @description User ID that starts with the u prefix.
             */
            user_id: string;
        };
        /** EchoRequest */
        EchoRequest: {
            /**
             * Message
             * @description Message to echo back.
             */
            message: string;
        };
        /** EchoResponse */
        EchoResponse: {
            /**
             * Message
             * @description Original message.
             */
            message: string;
            /**
             * Reversed
             * @description Reversed message.
             */
            reversed: string;
        };
        /**
         * ErrorResponse
         * @description Standard error envelope for auth routes.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Error detail message or structured error payload.
             */
            detail: string | {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Health status string.
             */
            status: string;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /**
             * Status
             * @description Health check status.
             */
            status: string;
        };
        /** JobItem */
        JobItem: {
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Progress */
            progress: number;
            /** Status */
            status: string;
        };
        /** LLMInsight */
        LLMInsight: {
            /** Confidence */
            confidence: number;
            /** Details */
            details: string;
            /** Id */
            id: string;
            /** Nodeid */
            nodeId: string;
            /** Nodename */
            nodeName: string;
            /** Summary */
            summary: string;
            /** Timestamp */
            timestamp: string;
            /** Type */
            type: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Email
             * Format: email
             * @description Account email for password-based login.
             */
            email: string;
            /**
             * Password
             * @description Plaintext password to verify.
             */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /**
             * Message
             * @description Human-readable response message.
             */
            message: string;
        };
        /** NodeAnalysis */
        NodeAnalysis: {
            /** Findings */
            findings: string[];
            /** Recommendations */
            recommendations: string[];
            /** Summary */
            summary: string;
        };
        /** NodeTelemetry */
        NodeTelemetry: {
            /** Egressmbps */
            egressMbps: number;
            /** Errorrate */
            errorRate: number;
            /** Ingressmbps */
            ingressMbps: number;
            /** Latencyms */
            latencyMs: number;
        };
        /** PasskeyAddFinishRequest */
        PasskeyAddFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by add/start.
             */
            flow_id: string;
        };
        /** PasskeyAddStartResponse */
        PasskeyAddStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for add passkey.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyFinishResponse */
        PasskeyFinishResponse: {
            /**
             * Device Id
             * @description Device ID that starts with the d prefix, empty when no device key is bound.
             */
            device_id: string;
            /**
             * Display Name
             * @description Optional display name for the user, not set by default.
             */
            display_name?: string | null;
            /**
             * Role
             * @description Server-side role for the user.
             */
            role: string;
            /**
             * User Id
             * @description User ID that starts with the u prefix.
             */
            user_id: string;
        };
        /** PasskeyInfo */
        PasskeyInfo: {
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp in UTC.
             */
            created_at: string;
            /**
             * Id
             * @description Internal passkey ID that starts with the k prefix.
             */
            id: string;
            /**
             * Last Used At
             * @description Last successful use timestamp.
             */
            last_used_at?: string | null;
            /**
             * Name
             * @description User-provided passkey name.
             */
            name?: string | null;
            /**
             * Revoked At
             * @description Revocation timestamp, if revoked.
             */
            revoked_at?: string | null;
        };
        /** PasskeyListResponse */
        PasskeyListResponse: {
            /**
             * Passkeys
             * @description Passkeys for the current user.
             */
            passkeys: components["schemas"]["PasskeyInfo"][];
        };
        /** PasskeyLoginFinishRequest */
        PasskeyLoginFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by login/start.
             */
            flow_id: string;
        };
        /** PasskeyLoginStartResponse */
        PasskeyLoginStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for login.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialRequestOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyRegisterFinishRequest */
        PasskeyRegisterFinishRequest: {
            /**
             * Credential
             * @description Browser PublicKeyCredential response as JSON.
             */
            credential: {
                [key: string]: unknown;
            };
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Flow Id
             * @description Flow ID returned by register/start.
             */
            flow_id: string;
        };
        /** PasskeyRegisterStartResponse */
        PasskeyRegisterStartResponse: {
            /**
             * Flow Id
             * @description Server-generated flow ID for registration.
             */
            flow_id: string;
            /**
             * Options
             * @description PublicKeyCredentialCreationOptions payload as a JSON-safe dict.
             */
            options: {
                [key: string]: unknown;
            };
        };
        /** PasskeyRenameRequest */
        PasskeyRenameRequest: {
            /**
             * Name
             * @description New passkey name. Null or empty to clear.
             */
            name?: string | null;
        };
        /** PasskeyRenameResponse */
        PasskeyRenameResponse: {
            /**
             * Id
             * @description Internal passkey ID.
             */
            id: string;
            /**
             * Name
             * @description Updated passkey name.
             */
            name?: string | null;
        };
        /** PasskeyRevokeResponse */
        PasskeyRevokeResponse: {
            /**
             * Message
             * @description Status message for the revocation action.
             */
            message: string;
        };
        /** PasswordResetConfirmSchema */
        PasswordResetConfirmSchema: {
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * New Password
             * @description New password to set for the account.
             */
            new_password: string;
            /**
             * Token
             * @description Password reset token issued by the server.
             */
            token: string;
        };
        /** PasswordResetRequestSchema */
        PasswordResetRequestSchema: {
            /**
             * Email
             * Format: email
             * @description Account email to send a reset token.
             */
            email: string;
        };
        /** PingResponse */
        PingResponse: {
            /**
             * Ok
             * @description True when the service is reachable.
             */
            ok: boolean;
        };
        /** RBACPolicy */
        RBACPolicy: {
            /** Id */
            id: string;
            /** Lastmodified */
            lastModified: string;
            /** Permissions */
            permissions: string[];
            /** Risklevel */
            riskLevel: string;
            /** Role */
            role: string;
            /** Scope */
            scope: string;
            /** Subject */
            subject: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Device Label
             * @description Optional label for the device.
             */
            device_label?: string | null;
            /**
             * Device Public Key Jwk
             * @description Optional device public key in JWK format to bind a device identity.
             */
            device_public_key_jwk?: {
                [key: string]: unknown;
            } | null;
            /**
             * Email
             * Format: email
             * @description Account email for password-based signup.
             */
            email: string;
            /**
             * Password
             * @description Plaintext password, hashed server-side.
             */
            password: string;
        };
        /** RootResponse */
        RootResponse: {
            /**
             * Message
             * @description Welcome message.
             */
            message: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Device Id */
            device_id: string;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role: string;
            /** Scopes */
            scopes: string[];
            /** User Id */
            user_id: string;
        };
        /** TopologyData */
        TopologyData: {
            /** Edges */
            edges: components["schemas"]["TopologyEdge"][];
            /** Lastupdated */
            lastUpdated: string;
            /** Nodes */
            nodes: components["schemas"]["TopologyNode"][];
            /** Scanstatus */
            scanStatus: string;
        };
        /** TopologyEdge */
        TopologyEdge: {
            /**
             * Animated
             * @default false
             */
            animated: boolean | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** TopologyNode */
        TopologyNode: {
            analysis?: components["schemas"]["NodeAnalysis"] | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Position */
            position: {
                [key: string]: unknown;
            };
            /** Serviceid */
            serviceId: string;
            /** Status */
            status: string;
            telemetry?: components["schemas"]["NodeTelemetry"] | null;
            /** Type */
            type: string;
        };
        /** UploadItem */
        UploadItem: {
            /** Byte Size */
            byte_size: number;
            /** Content Type */
            content_type: string;
            /** Created At */
            created_at: string;
            /** Extraction Job Id */
            extraction_job_id: string | null;
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vulnerability */
        Vulnerability: {
            /** Affectednode */
            affectedNode: string;
            /** Affectednodeid */
            affectedNodeId: string;
            /** Cve */
            cve?: string | null;
            /** Description */
            description: string;
            /** Discoveredat */
            discoveredAt: string;
            /** Id */
            id: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    get_insights_api_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMInsight"][];
                };
            };
        };
    };
    get_rbac_api_rbac_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RBACPolicy"][];
                };
            };
        };
    };
    revoke_rbac_api_rbac__node_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topology_api_topology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyData"];
                };
            };
        };
    };
    run_scan_api_topology_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyData"];
                };
            };
        };
    };
    isolate_node_api_topology__node_id__isolate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vulnerabilities_api_vulnerabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vulnerability"][];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceBindingResponse"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_finish_auth_passkey_add_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyAddFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid or expired flow, or WebAuthn verification error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_start_auth_passkey_add_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyAddStartResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_finish_auth_passkey_login_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyLoginFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid credentials, revoked passkey, or expired flow. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_start_auth_passkey_login_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyLoginStartResponse"];
                };
            };
        };
    };
    register_finish_auth_passkey_register_finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyRegisterFinishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyFinishResponse"];
                };
            };
            /** @description Invalid or expired flow, or invalid WebAuthn payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_start_auth_passkey_register_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRegisterStartResponse"];
                };
            };
            /** @description Invalid request or WebAuthn configuration error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    passkeys_list_auth_passkeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyListResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    passkey_rename_auth_passkeys__key_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeyRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRenameResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Passkey not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot rename a revoked passkey. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    passkey_revoke_auth_passkeys__key_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyRevokeResponse"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Passkey not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot revoke the last active passkey. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "LAST_PASSKEY",
                     *         "message": "Cannot revoke the last active passkey."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_confirm_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceBindingResponse"];
                };
            };
            /** @description Invalid or expired reset token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_request_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceBindingResponse"];
                };
            };
            /** @description Email already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    ingest_cadvisor_batch_cadvisor_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadvisorBatchPayloadSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_echo_demo_echo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EchoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EchoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_ping_demo_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    demo_sse_demo_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream with chunk and done events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": string;
                };
            };
            /** @description Missing or invalid device JWT. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Missing token"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    get_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobItem"][];
                };
            };
        };
    };
    chat_stream_llm_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_uploads_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadItem"][];
                };
            };
        };
    };
    create_upload_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
