import json
import logging
from typing import AsyncGenerator, Dict, Any

from langchain_core.messages import HumanMessage, SystemMessage, AIMessage, ToolMessage
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent
from pydantic import ValidationError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Session # Required type mapping

from app.agents.tools.telemetry import get_resource_spikes, get_resource_spikes_impl

logger = logging.getLogger(__name__)

# Base prompt for the context agent
SYSTEM_PROMPT = """You are a highly capable AI cybersecurity context agent embedded within Manifold, a continuous monitoring platform.
Your primary role is to assist security analysts in understanding system topology, detecting threats, and querying telemetry data.

You have access to a tool `get_resource_spikes` which accepts a `lookback_seconds` integer. Use this tool if the user asks about recent resource usage, anomalies, spikes, CPU usage, or memory usage involving containers.

If the user provides context about a node (e.g. they are investigating a specific service or looking at a specific alert), the context will be provided as SYSTEM information before their message. Incorporate this context into your response.

Always be concise, professional, and clear. Format your answers clearly using Markdown.
"""

async def stream_agent_response(
    user_msg: str, 
    context: Dict[str, Any] | None, 
    db: AsyncSession
) -> AsyncGenerator[Dict[str, Any], None]:
    """
    Streams a LangGraph ReAct agent response back to an SSE-compatible generator.
    """
    
    # 1. Initialize the LLM (Requires OPENAI_API_KEY environment variable set in typical LangChain setups)
    # We use a relatively fast and smart model.
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.1, max_tokens=2000)

    # 2. Wrapper for the tool to inject the AsyncSession
    async def injected_get_resource_spikes(lookback_seconds: int) -> str:
        """
        Checks for recent resource spikes (CPU or Memory) across all supervised containers in a given lookback window.
        """
        try:
            return await get_resource_spikes_impl(lookback_seconds, db)
        except Exception as e:
            logger.error(f"Error executing get_resource_spikes tool: {e}")
            return f"Error executing tool: {e}"

    # We dynamically bind the wrapped function to replace the underlying logic of the @tool decorated function
    # Langchain tools are objects, so we can override their func or _run mechanism.
    # The safest way in LangChain is to create a new tool instance or just use a standard function wrapped with @tool.
    from langchain_core.tools import tool
    
    @tool
    async def get_resource_spikes_tool(lookback_seconds: int) -> str:
        """
        Checks for recent resource spikes (CPU or Memory) across all supervised containers in a given lookback window.
        """
        return await injected_get_resource_spikes(lookback_seconds)

    tools = [get_resource_spikes_tool]
    
    # 3. Create the LangGraph ReAct agent
    agent = create_react_agent(llm, tools)
    
    # 4. Construct messages
    messages = [SystemMessage(content=SYSTEM_PROMPT)]
    
    if context:
        context_str = json.dumps(context, indent=2)
        messages.append(SystemMessage(content=f"User is currently viewing the following context in the dashboard:\n{context_str}"))
        
    messages.append(HumanMessage(content=user_msg))

    # 5. Stream from the agent
    # We will process outputs and yield them in a token-by-token format or chunk format matching the expected SSE protocol {"token": chunk}
    
    # By default, create_react_agent streaming yields (node_name, state_updates)
    # If we want to stream tokens from the LLM, we need a slightly different setup or to just forward intermediate messages.
    # For simplicity and to match the SSE expectation of SSE stream {"token": chunk}, 
    # we will use `astream_events` to get granular token streams from the LLM node.
    
    try:
        async for event in agent.astream_events({"messages": messages}, version="v2"):
            # We only want to stream tokens from the actual Chat Model response (not the tool's internal workings)
            kind = event["event"]
            
            # This captures the chunks being generated by the ChatOpenAI model
            if kind == "on_chat_model_stream":
                chunk = event["data"]["chunk"]
                if chunk.content and isinstance(chunk.content, str):
                    yield {"event": "message", "data": json.dumps({"token": chunk.content})}
                    
            elif kind == "on_tool_start":
                tool_name = event["name"]
                # Notify the user we are using a tool (in italic)
                yield {"event": "message", "data": json.dumps({"token": f"\n\n_Invoking tool `{tool_name}`..._\n\n"})}
                
    except Exception as e:
        logger.error(f"Error in LangGraph stream: {e}", exc_info=True)
        yield {"event": "message", "data": json.dumps({"token": f"\n\n**Error:** Failed to generate response ({str(e)})"})}
